name: tda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - networkx
  - pip
  - pip:
      - giotto-tda
      - imblearn
      - nbformat